# Development Dockerfile
FROM golang:1.26-alpine

RUN apk add --no-cache \
    ca-certificates \
    git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8000
ENV PUBSUB_EMULATOR_HOST=pubsub:8085

CMD ["go", "run", "."]

