gcloud functions deploy windower --gen2 \
  --runtime go126 \
  --region europe-west3 \
  --memory 256Mi \
  --source ../src/windower \
  --entry-point ProcessWindows \
  --trigger-http \
  --allow-unauthenticated \
  --network default \
  --subnet projects/faastreams/regions/europe-west3/subnetworks/default \
  --clear-vpc-connector \
  --update-labels=pipeline=faas \
  --env-vars-file ../env/gcloud-env-windower.yaml